debug: false

spring:
  datasource:
    url: jdbc:mysql://47.75.243.208:3306/intelligentjoy_advertising?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useTimezone=true&serverTimezone=GMT%2B8
    username: intelligentjoy
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#showSql
logging:
  level:
    com:
      intelligentjoy:
        advertising:
          api: info