debug: true

spring:
  datasource:
    url: jdbc:mysql://10.8.16.77:3306/intelligentjoy_advertising?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 10.8.17.4
    port: 6879
    password: het@redis
    database: 8
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    lettuce:
      shutdown-timeout: 100ms
      pool:
        max-wait: -1ms
        max-active: 8
        max-idle: 0
    ssl: false
    timeout: 30s

logging:
  level:
    com:
      intelligentjoy:
        advertising:
          api: debug