server:
  port: 18000
  servlet:
    context-path: /advertising
  tomcat:
    uri-encoding: UTF-8

application:
  name: intelligentjoy-advertising-api-web
  version: 0.0.1

logging:
  level:
    org:
      springframework: info

spring:
  profiles:
    active: dev
  jackson:
    date-format:  yyyy-MM-dd HH:mm:ss
    time-zone:  GMT+8
