debug: true

spring:
  datasource:
    url: jdbc:mysql://www.brucehome.cn:3306/intelligentjoy_advertising
    username: intelligentjoy
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
